        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Zone Name</th>
                    <th>Operation</th>
                </tr>
            </thead>
            <tbody>
                <?foreach($items as $item):?>
                <tr>
                    <td><?=$item->getName()?></td>
                    <td>
                        <a class="btn btn-default btn-xs" href="<?=$this->url('eqtracker/zone/edit',['zoneid' => $item->getId()])?>"><span class="fa fa-lg fa-edit"></span></a>
                        <a class="btn btn-default btn-xs" href="<?=$this->url('eqtracker/zone/delete',['zoneid' => $item->getId()])?>"><span class="fa fa-lg fa-times"></span></a>
                    </td>
                </tr>
                <?endforeach?>
            </tbody>
        </table>
