<? $this->inlineScript()->appendFile("/js/logparser.js")?>
<form method="post" id="parseForm" action="<?=$this->url(null,[],true)?>">
<div class="panel panel-default">
    <div class="panel-heading">Add Log File</div>
    <div class="panel-body">
        <div class="form-group">
            <label class="control-label">Log File Parser</label>
            <input type="file" class="form-control" name="logfile" id="logfile" />
        </div>
        <ul class="notifications list-group">
        </ul>
    </div>

    
    <div class="panel-footer">
        <button type="submit" class="btn btn-default">Parse File</button>
    </div>
</div>
</form>
<div class="well">
    <div class="form-group">
        <label class="control-label">Kill Log Macro:</label> <input class="form-control" onmouseup="return false;" onFocus="$(this).select()" type="text" value="/rsay &lt;&lt;KILL-LOG&gt;&gt; %t">
    </div>
</div>
    
