<form method="post" action="<?=$this->url(null,[],true)?>">
<div class="panel panel-default">
    <div class="panel-heading">Add Log File</div>
    <div class="panel-body">
        <div class="form-group">
            <label class="control-label">Log File for upload</label>
            <input type="file" class="form-control" name="logfile" />
        </div>
            <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%;">
              60%
            </div>
      </div>
    </div>


    <div class="panel-footer">
        <button type="submit" class="btn btn-default">Upload</button>
    </div>
</div>
</form>

<script>
    $(function(){
    var bar = $('.progress-bar');
    var status = $('#status');
    $('form').ajaxForm({
        beforeSend: function() {
            status.empty();
            var percentVal = '0%';
            bar.width(percentVal)
            bar.html(percentVal);
        },
        uploadProgress: function(event, position, total, percentComplete) {
            var percentVal = percentComplete + '%';
            bar.width(percentVal)
            bar.html(percentVal);
        },
        success: function() {
            var percentVal = '100%';
            bar.width(percentVal)
            bar.html(percentVal);
        },
        complete: function(xhr) {
                document.location.href = "/";
        }
    }); 
});
</script>