        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>NPC Name</th>
                    <th>Operation</th>
                </tr>
            </thead>
            <tbody>
                <?foreach($items as $item):?>
                <tr>
                    <td><?=$item->getName()?></td>
                    <td>
                        <a class="btn btn-default btn-xs" href="<?=$this->url('home/npc/edit',['npc' => $item->getId()])?>"><span class="fa fa-lg fa-edit"></span></a>
                        <a class="btn btn-default btn-xs" href="<?=$this->url('home/npc/delete',['npc' => $item->getId()])?>"><span class="fa fa-lg fa-times"></span></a>
                    </td>
                </tr>
                <?endforeach?>
            </tbody>
        </table>
