<?
    if(!isset($this->parameter)){
        $this->parameter = [];
    }
?>
<nav>
<?php if ($this->pageCount): ?>
<ul class="pagination">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
<li>
  <a href="<?php echo $this->url($this->route, [],['query' => array_merge($this->parameter,array('page' => $this->previous))],true); ?>">
    &lt; Previous
  </a>
</li>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
<li>
    <a href="<?php echo $this->url($this->route, [],['query' => array_merge($this->parameter,array('page' => $page))],true); ?>">
        <?php echo $page; ?>
    </a> 
</li>
  <?php else: ?>
<li class="active">
    <a href="<?php echo $this->url($this->route, [],['query' => array_merge($this->parameter,array('page' => $page))],true); ?>">
        <?php echo $page; ?>
    </a>
</li>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
<li>
  <a href="<?php echo $this->url($this->route, [],['query' => array_merge($this->parameter,array('page' => $this->next))],true); ?>">
    Next &gt;
  </a>
</li>
<?php endif; ?>
</ul>
<?php endif; ?>
</nav>