<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Name</th>
            <th>Zone</th>
            <th>Kill Time</th>
            <th>Spawn Type</th>
            <th>Spawn Time</th>
            <th>Operation</th>
        </tr>
        
    </thead>
    <tbody>
        <?foreach($npcs as $npc):?>
        <tr>
            <td><?=$npc->getNPC()->getName()?></td>
            <td><?=$npc->getNPC()->getZone()->getName()?></td>
            <td><?=$npc->getCrDate()->format("Y/m/d H:i:s")?></td>
            <td><?=$npc->getNPC()->getSpawnType()?></td>
            <td>
                <?if($npc->getSpawnTime() > (new \DateTime)):?>
                <div class="countdown" data-spawn="<?=$npc->getSpawnTime()->format("Y/m/d H:i:s")?>"></div>
                <?else:?>
                    <?switch($npc->getNPC()->getSpawnType()){
                        case 'WINDOW' : ?>
                WINDOW
                <div class="countdown text-success" data-spawn="<?=$npc->getSpawnTime()->add(new \DateInterval("PT".$npc->getSpawnInterval()."M"))->format("Y/m/d H:i:s")?>"></div>
                
                <?  break;
                        case 'FIX' : echo 'UP';break;
                    }?>
                <?endif?>
            </td>
            <td>
                <a href="<?=$this->url('eqtracker/removekill',['npc' => $npc->getNPC()->getId()])?>" class="btn btn-default btn-xs"><span class="fa fa-lg fa-times"></span></a>
            </td>
        </tr>
        <?endforeach?>
    </tbody>
</table>

<script>
    $(function(){
        $(".countdown").each(function(){
            $(this).countdown($(this).attr('data-spawn'),function(event) {
                $(this).html(event.strftime('%D days %H:%M:%S'));
            });
        });

    });
    </script>